defaults:
- _self_
- model@_global_ : baseline
- dataset@_global_ : geolife
- evaluation@_global_: baseline

cuda_number: 1
exp_name: default

hydra_logging: disabled
hydra:
  run:
    dir: /data/logs/${now:%Y-%m-%d_%H-%M-%S}